// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhPIiePpfhtLdKzo82eoKVDEEs8qLaAlY',
    appId: '1:43829310739:web:cb462a3edaaa2175b656e6',
    messagingSenderId: '43829310739',
    projectId: 'push-noti-d6853',
    authDomain: 'push-noti-d6853.firebaseapp.com',
    storageBucket: 'push-noti-d6853.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHmmkt68AVgcusN9G7TqdnFEhW1V8mGj0',
    appId: '1:43829310739:android:7722af56c078f4cab656e6',
    messagingSenderId: '43829310739',
    projectId: 'push-noti-d6853',
    storageBucket: 'push-noti-d6853.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5_87tcgcfvdn8sUKROUBHTeiJ3hz6-fY',
    appId: '1:43829310739:ios:841b8d24eb138ea8b656e6',
    messagingSenderId: '43829310739',
    projectId: 'push-noti-d6853',
    storageBucket: 'push-noti-d6853.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotiTes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5_87tcgcfvdn8sUKROUBHTeiJ3hz6-fY',
    appId: '1:43829310739:ios:841b8d24eb138ea8b656e6',
    messagingSenderId: '43829310739',
    projectId: 'push-noti-d6853',
    storageBucket: 'push-noti-d6853.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotiTes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhPIiePpfhtLdKzo82eoKVDEEs8qLaAlY',
    appId: '1:43829310739:web:72a68fd201c4687cb656e6',
    messagingSenderId: '43829310739',
    projectId: 'push-noti-d6853',
    authDomain: 'push-noti-d6853.firebaseapp.com',
    storageBucket: 'push-noti-d6853.firebasestorage.app',
  );
}
